add --fallbackmode to handily set a mode to files, due to metadata un…
yunify/qsfs-fuse pull request #2
Opened 2018-03-20 07:36 UTC by aligo

…supported by skd

or hope to support metadata early

2018-03-20 16:52 UTC, frostyplanet commented
what do you mean by "skd" ?

2018-03-21 02:29 UTC, aligo commented
@frostyplanet here it comes: https://github.com/yunify/qsfs-fuse/blob/7fd39a74499712a2ed18b7a6ac2f377fa4763c9a/src/client/QSClientConverter.cpp#L158

2018-03-21 02:38 UTC, aligo commented
In my case, want to mount qsfs in fstab, which would made qsfs process run as root, meanwhile my app runs as another user, can't have a proper access to files defined mode 0644 and uid/gid both mismatched.

2018-03-21 06:11 UTC, frostyplanet commented
skd actually a typo of SDK ...

2018-03-21 09:02 UTC, jimhuaang requested changes
Looks good. I have a few comments that should be addressed before this request get merged.

2018-03-21 09:02 UTC, jimhuaang commented on src/filesystem/Parser.cpp
> +  mode_t fallbackMode;     // default fallback mode
What does fallback means here? Seems "fallbackMode" is not a great name. what we are doing here is to provide a option to specifying a file mode (OCTAL-MODE format), I think we could just name it fileMode or some other name which can clearly show the intention.

2018-03-21 09:02 UTC, jimhuaang commented on src/filesystem/Parser.cpp
> +  mode_t fallbackMode;     // default fallback mode
And could you also update the docs in HelpText.cpp::ShowQSFSHelp and HelpText.cpp::ShowQSFSUsage?

2018-03-21 09:02 UTC, jimhuaang commented on src/filesystem/Parser.cpp
> +  mode_t fallbackMode;     // default fallback mode
I think this option is relating to the stat, we better group this new option with other stat releated options (maxstat and statexpire). I mean we better to add this new option following statexpire, this also applies to your changes in other files.

2018-03-21 10:20 UTC, aligo commented
@jimhuaang fallbackmode => filemode, Put it above network related options.

2018-03-21 10:23 UTC, jimhuaang commented on src/filesystem/HelpText.cpp
> +  "                     is " << ModeToString(QS::Configure::Options::Instance().GetFileMode()) << " times\n"
there is a typo, " times" is not needed here

2018-03-21 10:24 UTC, jimhuaang requested changes
Please see the comments, there is a typo

2018-03-21 10:45 UTC, jimhuaang requested changes
Please also replace GetDefineDirMode, GetDefineFileMode used  in other places (FileMetaData.cpp, Operations.cpp) with your new code (GetFileMode).

2018-03-21 11:06 UTC, jimhuaang requested changes
Utils.cpp still have one GetDefineDirMode need to be replaced. thanks.

2018-03-21 11:29 UTC, aligo commented
That one looks like used to create local directory, keep that way would be ok.

2018-03-21 14:28 UTC, jimhuaang approved these changes

2018-03-21 14:37 UTC, merged